[2023-11-06 00:00:09,234] {processor.py:153} INFO - Started process (PID=6366) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:00:09,235] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:00:09,236] {logging_mixin.py:115} INFO - [2023-11-06 00:00:09,236] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:00:09,316] {logging_mixin.py:115} INFO - [2023-11-06 00:00:09,315] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:00:09,316] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:00:09,336] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.105 seconds
[2023-11-06 00:00:39,560] {processor.py:153} INFO - Started process (PID=6421) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:00:39,563] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:00:39,564] {logging_mixin.py:115} INFO - [2023-11-06 00:00:39,564] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:00:39,646] {logging_mixin.py:115} INFO - [2023-11-06 00:00:39,645] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:00:39,647] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:00:39,667] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.111 seconds
[2023-11-06 00:01:09,750] {processor.py:153} INFO - Started process (PID=6485) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:01:09,751] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:01:09,752] {logging_mixin.py:115} INFO - [2023-11-06 00:01:09,752] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:01:09,837] {logging_mixin.py:115} INFO - [2023-11-06 00:01:09,835] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:01:09,838] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:01:09,865] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.119 seconds
[2023-11-06 00:01:39,908] {processor.py:153} INFO - Started process (PID=6549) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:01:39,909] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:01:39,910] {logging_mixin.py:115} INFO - [2023-11-06 00:01:39,910] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:01:40,005] {logging_mixin.py:115} INFO - [2023-11-06 00:01:40,004] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:01:40,006] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:01:40,028] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.124 seconds
[2023-11-06 00:02:10,556] {processor.py:153} INFO - Started process (PID=6604) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:02:10,557] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:02:10,558] {logging_mixin.py:115} INFO - [2023-11-06 00:02:10,558] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:02:10,661] {logging_mixin.py:115} INFO - [2023-11-06 00:02:10,659] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:02:10,661] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:02:10,692] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.140 seconds
[2023-11-06 00:02:40,995] {processor.py:153} INFO - Started process (PID=6670) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:02:40,996] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:02:40,997] {logging_mixin.py:115} INFO - [2023-11-06 00:02:40,997] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:02:41,103] {logging_mixin.py:115} INFO - [2023-11-06 00:02:41,102] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:02:41,104] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:02:41,130] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.141 seconds
[2023-11-06 00:03:11,255] {processor.py:153} INFO - Started process (PID=6734) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:03:11,256] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:03:11,257] {logging_mixin.py:115} INFO - [2023-11-06 00:03:11,257] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:03:11,374] {logging_mixin.py:115} INFO - [2023-11-06 00:03:11,372] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:03:11,375] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:03:11,403] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.154 seconds
[2023-11-06 00:03:41,873] {processor.py:153} INFO - Started process (PID=6789) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:03:41,875] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:03:41,876] {logging_mixin.py:115} INFO - [2023-11-06 00:03:41,876] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:03:42,008] {logging_mixin.py:115} INFO - [2023-11-06 00:03:42,005] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:03:42,010] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:03:42,039] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.171 seconds
[2023-11-06 00:04:12,459] {processor.py:153} INFO - Started process (PID=6853) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:04:12,460] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:04:12,462] {logging_mixin.py:115} INFO - [2023-11-06 00:04:12,461] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:04:12,598] {logging_mixin.py:115} INFO - [2023-11-06 00:04:12,597] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:04:12,599] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:04:12,632] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.179 seconds
[2023-11-06 00:04:42,673] {processor.py:153} INFO - Started process (PID=6908) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:04:42,673] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:04:42,674] {logging_mixin.py:115} INFO - [2023-11-06 00:04:42,674] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:04:42,763] {logging_mixin.py:115} INFO - [2023-11-06 00:04:42,762] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:04:42,764] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:04:42,783] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.114 seconds
[2023-11-06 00:05:13,008] {processor.py:153} INFO - Started process (PID=6974) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:05:13,009] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:05:13,011] {logging_mixin.py:115} INFO - [2023-11-06 00:05:13,011] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:05:13,171] {logging_mixin.py:115} INFO - [2023-11-06 00:05:13,170] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:05:13,172] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:05:13,204] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.200 seconds
[2023-11-06 00:05:43,305] {processor.py:153} INFO - Started process (PID=7038) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:05:43,306] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:05:43,307] {logging_mixin.py:115} INFO - [2023-11-06 00:05:43,307] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:05:43,517] {logging_mixin.py:115} INFO - [2023-11-06 00:05:43,516] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:05:43,520] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:05:43,682] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.382 seconds
[2023-11-06 00:06:14,354] {processor.py:153} INFO - Started process (PID=7099) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:06:14,355] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:06:14,356] {logging_mixin.py:115} INFO - [2023-11-06 00:06:14,356] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:06:14,436] {logging_mixin.py:115} INFO - [2023-11-06 00:06:14,435] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:06:14,437] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:06:14,457] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.106 seconds
[2023-11-06 00:06:44,636] {processor.py:153} INFO - Started process (PID=7164) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:06:44,637] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:06:44,640] {logging_mixin.py:115} INFO - [2023-11-06 00:06:44,640] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:06:44,785] {logging_mixin.py:115} INFO - [2023-11-06 00:06:44,781] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:06:44,790] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:06:44,867] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.236 seconds
[2023-11-06 00:07:14,928] {processor.py:153} INFO - Started process (PID=7227) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:07:14,929] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:07:14,930] {logging_mixin.py:115} INFO - [2023-11-06 00:07:14,930] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:07:15,029] {logging_mixin.py:115} INFO - [2023-11-06 00:07:15,028] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:07:15,030] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:07:15,050] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.125 seconds
[2023-11-06 00:07:45,133] {processor.py:153} INFO - Started process (PID=7282) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:07:45,134] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:07:45,135] {logging_mixin.py:115} INFO - [2023-11-06 00:07:45,135] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:07:45,231] {logging_mixin.py:115} INFO - [2023-11-06 00:07:45,229] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:07:45,232] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:07:45,254] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.125 seconds
[2023-11-06 00:08:15,824] {processor.py:153} INFO - Started process (PID=7346) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:08:15,825] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:08:15,826] {logging_mixin.py:115} INFO - [2023-11-06 00:08:15,826] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:08:15,933] {logging_mixin.py:115} INFO - [2023-11-06 00:08:15,931] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:08:15,933] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:08:15,960] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.141 seconds
[2023-11-06 00:08:46,113] {processor.py:153} INFO - Started process (PID=7401) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:08:46,114] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:08:46,115] {logging_mixin.py:115} INFO - [2023-11-06 00:08:46,115] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:08:46,207] {logging_mixin.py:115} INFO - [2023-11-06 00:08:46,206] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:08:46,208] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:08:46,231] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.122 seconds
[2023-11-06 00:09:16,301] {processor.py:153} INFO - Started process (PID=7465) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:09:16,302] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:09:16,303] {logging_mixin.py:115} INFO - [2023-11-06 00:09:16,303] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:09:16,407] {logging_mixin.py:115} INFO - [2023-11-06 00:09:16,406] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:09:16,408] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:09:16,433] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.136 seconds
[2023-11-06 00:09:46,526] {processor.py:153} INFO - Started process (PID=7529) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:09:46,527] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:09:46,527] {logging_mixin.py:115} INFO - [2023-11-06 00:09:46,527] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:09:46,625] {logging_mixin.py:115} INFO - [2023-11-06 00:09:46,623] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:09:46,625] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:09:46,656] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.134 seconds
[2023-11-06 00:10:16,876] {processor.py:153} INFO - Started process (PID=7586) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:10:16,887] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:10:16,915] {logging_mixin.py:115} INFO - [2023-11-06 00:10:16,914] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:10:17,015] {logging_mixin.py:115} INFO - [2023-11-06 00:10:17,014] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:10:17,016] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:10:17,039] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.172 seconds
[2023-11-06 00:10:47,065] {processor.py:153} INFO - Started process (PID=7652) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:10:47,066] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:10:47,067] {logging_mixin.py:115} INFO - [2023-11-06 00:10:47,067] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:10:47,177] {logging_mixin.py:115} INFO - [2023-11-06 00:10:47,176] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:10:47,179] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:10:47,208] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.148 seconds
[2023-11-06 00:11:17,511] {processor.py:153} INFO - Started process (PID=7707) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:11:17,515] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:11:17,516] {logging_mixin.py:115} INFO - [2023-11-06 00:11:17,516] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:11:17,619] {logging_mixin.py:115} INFO - [2023-11-06 00:11:17,618] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:11:17,620] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:11:17,644] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.137 seconds
[2023-11-06 00:11:47,813] {processor.py:153} INFO - Started process (PID=7771) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:11:47,813] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:11:47,814] {logging_mixin.py:115} INFO - [2023-11-06 00:11:47,814] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:11:47,903] {logging_mixin.py:115} INFO - [2023-11-06 00:11:47,902] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:11:47,904] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:11:47,926] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.117 seconds
[2023-11-06 00:12:18,047] {processor.py:153} INFO - Started process (PID=7835) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:12:18,048] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:12:18,050] {logging_mixin.py:115} INFO - [2023-11-06 00:12:18,049] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:12:18,165] {logging_mixin.py:115} INFO - [2023-11-06 00:12:18,163] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:12:18,165] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:12:18,195] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.153 seconds
[2023-11-06 00:12:48,406] {processor.py:153} INFO - Started process (PID=7890) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:12:48,407] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:12:48,408] {logging_mixin.py:115} INFO - [2023-11-06 00:12:48,408] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:12:48,505] {logging_mixin.py:115} INFO - [2023-11-06 00:12:48,503] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:12:48,505] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:12:48,528] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.126 seconds
[2023-11-06 00:13:18,880] {processor.py:153} INFO - Started process (PID=7955) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:13:18,881] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:13:18,882] {logging_mixin.py:115} INFO - [2023-11-06 00:13:18,882] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:13:18,967] {logging_mixin.py:115} INFO - [2023-11-06 00:13:18,966] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:13:18,967] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:13:18,988] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.111 seconds
[2023-11-06 00:13:49,233] {processor.py:153} INFO - Started process (PID=8017) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:13:49,234] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:13:49,235] {logging_mixin.py:115} INFO - [2023-11-06 00:13:49,235] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:13:49,351] {logging_mixin.py:115} INFO - [2023-11-06 00:13:49,349] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:13:49,352] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:13:49,378] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.150 seconds
[2023-11-06 00:14:19,707] {processor.py:153} INFO - Started process (PID=8074) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:14:19,708] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:14:19,709] {logging_mixin.py:115} INFO - [2023-11-06 00:14:19,709] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:14:19,802] {logging_mixin.py:115} INFO - [2023-11-06 00:14:19,800] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:14:19,802] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:14:19,824] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.121 seconds
[2023-11-06 00:14:49,939] {processor.py:153} INFO - Started process (PID=8138) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:14:49,940] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:14:49,941] {logging_mixin.py:115} INFO - [2023-11-06 00:14:49,941] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:14:50,025] {logging_mixin.py:115} INFO - [2023-11-06 00:14:50,024] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:14:50,026] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:14:50,046] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.110 seconds
[2023-11-06 00:15:20,807] {processor.py:153} INFO - Started process (PID=8193) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:15:20,807] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:15:20,808] {logging_mixin.py:115} INFO - [2023-11-06 00:15:20,808] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:15:20,887] {logging_mixin.py:115} INFO - [2023-11-06 00:15:20,885] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:15:20,887] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:15:20,907] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.103 seconds
[2023-11-06 00:15:51,163] {processor.py:153} INFO - Started process (PID=8257) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:15:51,164] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:15:51,165] {logging_mixin.py:115} INFO - [2023-11-06 00:15:51,165] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:15:51,257] {logging_mixin.py:115} INFO - [2023-11-06 00:15:51,256] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:15:51,258] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:15:51,280] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.122 seconds
[2023-11-06 00:16:21,676] {processor.py:153} INFO - Started process (PID=8323) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:16:21,677] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:16:21,678] {logging_mixin.py:115} INFO - [2023-11-06 00:16:21,678] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:16:21,801] {logging_mixin.py:115} INFO - [2023-11-06 00:16:21,799] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:16:21,802] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:16:21,834] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.164 seconds
[2023-11-06 00:16:51,921] {processor.py:153} INFO - Started process (PID=8377) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:16:51,922] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:16:51,923] {logging_mixin.py:115} INFO - [2023-11-06 00:16:51,923] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:16:52,009] {logging_mixin.py:115} INFO - [2023-11-06 00:16:52,008] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:16:52,010] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:16:52,031] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.113 seconds
[2023-11-06 00:17:22,735] {processor.py:153} INFO - Started process (PID=8441) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:17:22,736] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:17:22,737] {logging_mixin.py:115} INFO - [2023-11-06 00:17:22,737] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:17:22,814] {logging_mixin.py:115} INFO - [2023-11-06 00:17:22,813] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:17:22,814] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:17:22,834] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.102 seconds
[2023-11-06 00:17:53,390] {processor.py:153} INFO - Started process (PID=8505) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:17:53,391] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:17:53,391] {logging_mixin.py:115} INFO - [2023-11-06 00:17:53,391] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:17:53,469] {logging_mixin.py:115} INFO - [2023-11-06 00:17:53,468] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:17:53,470] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:17:53,491] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.105 seconds
[2023-11-06 00:18:23,961] {processor.py:153} INFO - Started process (PID=8560) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:18:23,962] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:18:23,963] {logging_mixin.py:115} INFO - [2023-11-06 00:18:23,963] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:18:24,041] {logging_mixin.py:115} INFO - [2023-11-06 00:18:24,040] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:18:24,042] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:18:24,062] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.104 seconds
[2023-11-06 00:18:54,640] {processor.py:153} INFO - Started process (PID=8624) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:18:54,641] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:18:54,641] {logging_mixin.py:115} INFO - [2023-11-06 00:18:54,641] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:18:54,718] {logging_mixin.py:115} INFO - [2023-11-06 00:18:54,717] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:18:54,719] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:18:54,739] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.102 seconds
[2023-11-06 00:19:25,352] {processor.py:153} INFO - Started process (PID=8688) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:19:25,353] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:19:25,353] {logging_mixin.py:115} INFO - [2023-11-06 00:19:25,353] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:19:25,439] {logging_mixin.py:115} INFO - [2023-11-06 00:19:25,437] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:19:25,440] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:19:25,460] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.111 seconds
[2023-11-06 00:19:55,847] {processor.py:153} INFO - Started process (PID=8750) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:19:55,848] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:19:55,848] {logging_mixin.py:115} INFO - [2023-11-06 00:19:55,848] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:19:55,928] {logging_mixin.py:115} INFO - [2023-11-06 00:19:55,927] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:19:55,929] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:19:55,950] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.107 seconds
[2023-11-06 00:20:26,444] {processor.py:153} INFO - Started process (PID=8807) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:20:26,445] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:20:26,445] {logging_mixin.py:115} INFO - [2023-11-06 00:20:26,445] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:20:26,525] {logging_mixin.py:115} INFO - [2023-11-06 00:20:26,524] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:20:26,535] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:20:26,555] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.114 seconds
[2023-11-06 00:20:56,992] {processor.py:153} INFO - Started process (PID=8871) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:20:56,993] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:20:56,994] {logging_mixin.py:115} INFO - [2023-11-06 00:20:56,994] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:20:57,076] {logging_mixin.py:115} INFO - [2023-11-06 00:20:57,075] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:20:57,076] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:20:57,097] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.108 seconds
[2023-11-06 00:21:27,583] {processor.py:153} INFO - Started process (PID=8935) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:21:27,584] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:21:27,584] {logging_mixin.py:115} INFO - [2023-11-06 00:21:27,584] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:21:27,662] {logging_mixin.py:115} INFO - [2023-11-06 00:21:27,661] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:21:27,663] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:21:27,684] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.104 seconds
[2023-11-06 00:21:58,157] {processor.py:153} INFO - Started process (PID=8990) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:21:58,158] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:21:58,159] {logging_mixin.py:115} INFO - [2023-11-06 00:21:58,159] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:21:58,237] {logging_mixin.py:115} INFO - [2023-11-06 00:21:58,236] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:21:58,238] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:21:58,257] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.103 seconds
[2023-11-06 00:22:28,657] {processor.py:153} INFO - Started process (PID=9054) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:22:28,657] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:22:28,658] {logging_mixin.py:115} INFO - [2023-11-06 00:22:28,658] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:22:28,738] {logging_mixin.py:115} INFO - [2023-11-06 00:22:28,737] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:22:28,739] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:22:28,760] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.106 seconds
[2023-11-06 00:22:59,370] {processor.py:153} INFO - Started process (PID=9118) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:22:59,388] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:22:59,389] {logging_mixin.py:115} INFO - [2023-11-06 00:22:59,389] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:22:59,465] {logging_mixin.py:115} INFO - [2023-11-06 00:22:59,464] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:22:59,466] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:22:59,489] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.122 seconds
[2023-11-06 00:23:29,920] {processor.py:153} INFO - Started process (PID=9182) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:23:29,920] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:23:29,921] {logging_mixin.py:115} INFO - [2023-11-06 00:23:29,921] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:23:30,001] {logging_mixin.py:115} INFO - [2023-11-06 00:23:30,000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:23:30,002] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:23:30,022] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.106 seconds
[2023-11-06 00:24:00,620] {processor.py:153} INFO - Started process (PID=9237) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:24:00,620] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:24:00,621] {logging_mixin.py:115} INFO - [2023-11-06 00:24:00,621] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:24:00,702] {logging_mixin.py:115} INFO - [2023-11-06 00:24:00,701] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:24:00,703] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:24:00,724] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.108 seconds
[2023-11-06 00:24:31,193] {processor.py:153} INFO - Started process (PID=9301) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:24:31,193] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:24:31,194] {logging_mixin.py:115} INFO - [2023-11-06 00:24:31,194] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:24:31,273] {logging_mixin.py:115} INFO - [2023-11-06 00:24:31,272] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:24:31,274] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:24:31,293] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.104 seconds
[2023-11-06 00:25:01,961] {processor.py:153} INFO - Started process (PID=9365) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:25:01,962] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:25:01,962] {logging_mixin.py:115} INFO - [2023-11-06 00:25:01,962] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:25:02,042] {logging_mixin.py:115} INFO - [2023-11-06 00:25:02,041] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:25:02,043] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:25:02,062] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.105 seconds
[2023-11-06 00:41:15,120] {processor.py:153} INFO - Started process (PID=9417) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:41:15,121] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:41:15,122] {logging_mixin.py:115} INFO - [2023-11-06 00:41:15,122] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:41:15,241] {logging_mixin.py:115} INFO - [2023-11-06 00:41:15,240] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:41:15,242] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:41:15,350] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.234 seconds
[2023-11-06 00:41:46,362] {processor.py:153} INFO - Started process (PID=9472) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:41:46,370] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:41:46,379] {logging_mixin.py:115} INFO - [2023-11-06 00:41:46,378] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:41:46,993] {logging_mixin.py:115} INFO - [2023-11-06 00:41:46,988] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:41:46,997] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:41:47,106] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.775 seconds
[2023-11-06 00:59:57,553] {processor.py:153} INFO - Started process (PID=9520) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:59:57,575] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 00:59:57,577] {logging_mixin.py:115} INFO - [2023-11-06 00:59:57,577] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:59:57,783] {logging_mixin.py:115} INFO - [2023-11-06 00:59:57,781] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 00:59:57,784] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 00:59:57,851] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.317 seconds
[2023-11-06 01:00:28,683] {processor.py:153} INFO - Started process (PID=9573) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:00:28,699] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:00:28,705] {logging_mixin.py:115} INFO - [2023-11-06 01:00:28,704] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:00:29,499] {logging_mixin.py:115} INFO - [2023-11-06 01:00:29,479] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:00:29,504] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:00:29,721] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.067 seconds
[2023-11-06 01:01:00,026] {processor.py:153} INFO - Started process (PID=9620) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:01:00,032] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:01:00,052] {logging_mixin.py:115} INFO - [2023-11-06 01:01:00,051] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:01:00,725] {logging_mixin.py:115} INFO - [2023-11-06 01:01:00,719] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:01:00,728] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:01:00,853] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.875 seconds
[2023-11-06 01:01:31,287] {processor.py:153} INFO - Started process (PID=9675) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:01:31,298] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:01:31,321] {logging_mixin.py:115} INFO - [2023-11-06 01:01:31,321] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:01:31,801] {logging_mixin.py:115} INFO - [2023-11-06 01:01:31,794] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:01:31,804] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:01:31,906] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.637 seconds
[2023-11-06 01:02:02,608] {processor.py:153} INFO - Started process (PID=9721) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:02:02,611] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:02:02,616] {logging_mixin.py:115} INFO - [2023-11-06 01:02:02,615] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:02:03,269] {logging_mixin.py:115} INFO - [2023-11-06 01:02:03,264] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:02:03,271] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:02:03,378] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.797 seconds
[2023-11-06 01:02:33,567] {processor.py:153} INFO - Started process (PID=9776) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:02:33,572] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:02:33,577] {logging_mixin.py:115} INFO - [2023-11-06 01:02:33,576] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:02:34,197] {logging_mixin.py:115} INFO - [2023-11-06 01:02:34,185] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:02:34,202] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:02:34,339] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.795 seconds
[2023-11-06 01:03:04,787] {processor.py:153} INFO - Started process (PID=9823) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:03:04,792] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:03:04,797] {logging_mixin.py:115} INFO - [2023-11-06 01:03:04,796] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:03:05,314] {logging_mixin.py:115} INFO - [2023-11-06 01:03:05,309] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:03:05,317] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:03:05,416] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.646 seconds
[2023-11-06 01:03:35,759] {processor.py:153} INFO - Started process (PID=9878) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:03:35,762] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:03:35,767] {logging_mixin.py:115} INFO - [2023-11-06 01:03:35,766] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:03:36,531] {logging_mixin.py:115} INFO - [2023-11-06 01:03:36,524] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:03:36,535] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:03:36,675] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.948 seconds
[2023-11-06 01:04:07,476] {processor.py:153} INFO - Started process (PID=9931) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:04:07,481] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:04:07,489] {logging_mixin.py:115} INFO - [2023-11-06 01:04:07,488] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:04:09,560] {logging_mixin.py:115} INFO - [2023-11-06 01:04:09,534] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:04:09,565] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:04:09,823] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 2.375 seconds
[2023-11-06 01:34:34,674] {processor.py:153} INFO - Started process (PID=9988) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:34:34,676] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:34:34,682] {logging_mixin.py:115} INFO - [2023-11-06 01:34:34,682] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:34:34,847] {logging_mixin.py:115} INFO - [2023-11-06 01:34:34,845] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:34:34,848] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:34:34,894] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.240 seconds
[2023-11-06 01:35:05,531] {processor.py:153} INFO - Started process (PID=10033) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:35:05,536] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:35:05,540] {logging_mixin.py:115} INFO - [2023-11-06 01:35:05,540] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:35:06,311] {logging_mixin.py:115} INFO - [2023-11-06 01:35:06,296] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:35:06,320] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:35:06,487] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.976 seconds
[2023-11-06 01:35:36,822] {processor.py:153} INFO - Started process (PID=10089) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:35:36,825] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:35:36,829] {logging_mixin.py:115} INFO - [2023-11-06 01:35:36,828] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:35:37,629] {logging_mixin.py:115} INFO - [2023-11-06 01:35:37,623] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:35:37,632] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:35:37,819] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.020 seconds
[2023-11-06 01:36:08,293] {processor.py:153} INFO - Started process (PID=10135) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:36:08,298] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:36:08,320] {logging_mixin.py:115} INFO - [2023-11-06 01:36:08,319] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:36:09,548] {logging_mixin.py:115} INFO - [2023-11-06 01:36:09,536] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:36:09,570] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:36:09,782] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.509 seconds
[2023-11-06 01:36:40,283] {processor.py:153} INFO - Started process (PID=10190) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:36:40,287] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:36:40,291] {logging_mixin.py:115} INFO - [2023-11-06 01:36:40,291] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:36:40,725] {logging_mixin.py:115} INFO - [2023-11-06 01:36:40,720] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:36:40,728] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:36:40,826] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.560 seconds
[2023-11-06 01:37:11,441] {processor.py:153} INFO - Started process (PID=10245) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:37:11,445] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:37:11,450] {logging_mixin.py:115} INFO - [2023-11-06 01:37:11,449] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:37:11,936] {logging_mixin.py:115} INFO - [2023-11-06 01:37:11,931] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:37:11,939] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:37:12,056] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.633 seconds
[2023-11-06 01:37:42,226] {processor.py:153} INFO - Started process (PID=10291) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:37:42,229] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:37:42,233] {logging_mixin.py:115} INFO - [2023-11-06 01:37:42,233] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:37:42,651] {logging_mixin.py:115} INFO - [2023-11-06 01:37:42,646] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:37:42,653] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:37:42,775] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.571 seconds
[2023-11-06 01:54:54,255] {processor.py:153} INFO - Started process (PID=10350) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:54:54,256] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:54:54,257] {logging_mixin.py:115} INFO - [2023-11-06 01:54:54,257] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:54:54,608] {logging_mixin.py:115} INFO - [2023-11-06 01:54:54,606] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:54:54,609] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:54:54,646] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.397 seconds
[2023-11-06 01:55:25,500] {processor.py:153} INFO - Started process (PID=10406) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:55:25,514] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:55:25,528] {logging_mixin.py:115} INFO - [2023-11-06 01:55:25,525] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:55:27,851] {logging_mixin.py:115} INFO - [2023-11-06 01:55:27,844] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:55:27,855] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:55:27,984] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 2.580 seconds
[2023-11-06 01:55:58,131] {processor.py:153} INFO - Started process (PID=10451) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:55:58,134] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:55:58,140] {logging_mixin.py:115} INFO - [2023-11-06 01:55:58,139] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:55:59,266] {logging_mixin.py:115} INFO - [2023-11-06 01:55:59,259] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:55:59,269] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:55:59,372] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.265 seconds
[2023-11-06 01:56:30,082] {processor.py:153} INFO - Started process (PID=10506) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:56:30,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:56:30,089] {logging_mixin.py:115} INFO - [2023-11-06 01:56:30,088] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:56:31,002] {logging_mixin.py:115} INFO - [2023-11-06 01:56:30,995] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:56:31,006] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:56:31,099] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.034 seconds
[2023-11-06 01:57:01,283] {processor.py:153} INFO - Started process (PID=10561) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:57:01,288] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:57:01,293] {logging_mixin.py:115} INFO - [2023-11-06 01:57:01,293] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:57:02,286] {logging_mixin.py:115} INFO - [2023-11-06 01:57:02,280] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:57:02,290] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:57:02,371] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.108 seconds
[2023-11-06 01:57:32,565] {processor.py:153} INFO - Started process (PID=10616) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:57:32,569] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:57:32,573] {logging_mixin.py:115} INFO - [2023-11-06 01:57:32,573] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:57:33,673] {logging_mixin.py:115} INFO - [2023-11-06 01:57:33,667] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:57:33,678] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:57:33,790] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.248 seconds
[2023-11-06 01:58:03,929] {processor.py:153} INFO - Started process (PID=10663) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:58:03,934] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:58:03,942] {logging_mixin.py:115} INFO - [2023-11-06 01:58:03,941] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:58:05,225] {logging_mixin.py:115} INFO - [2023-11-06 01:58:05,219] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:58:05,230] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:58:05,356] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.454 seconds
[2023-11-06 01:58:36,008] {processor.py:153} INFO - Started process (PID=10719) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:58:36,013] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:58:36,019] {logging_mixin.py:115} INFO - [2023-11-06 01:58:36,018] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:58:36,905] {logging_mixin.py:115} INFO - [2023-11-06 01:58:36,900] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:58:36,930] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:58:37,017] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.031 seconds
[2023-11-06 01:59:07,509] {processor.py:153} INFO - Started process (PID=10775) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:59:07,521] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:59:07,531] {logging_mixin.py:115} INFO - [2023-11-06 01:59:07,531] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:59:09,179] {logging_mixin.py:115} INFO - [2023-11-06 01:59:09,173] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:59:09,183] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:59:09,353] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.876 seconds
[2023-11-06 01:59:39,527] {processor.py:153} INFO - Started process (PID=10821) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:59:39,531] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 01:59:39,535] {logging_mixin.py:115} INFO - [2023-11-06 01:59:39,534] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:59:40,495] {logging_mixin.py:115} INFO - [2023-11-06 01:59:40,489] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 01:59:40,500] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 01:59:40,627] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.123 seconds
[2023-11-06 02:00:10,829] {processor.py:153} INFO - Started process (PID=10875) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:00:10,833] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:00:10,838] {logging_mixin.py:115} INFO - [2023-11-06 02:00:10,838] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:00:11,868] {logging_mixin.py:115} INFO - [2023-11-06 02:00:11,863] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:00:11,871] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:00:12,016] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.207 seconds
[2023-11-06 02:00:42,556] {processor.py:153} INFO - Started process (PID=10921) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:00:42,559] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:00:42,564] {logging_mixin.py:115} INFO - [2023-11-06 02:00:42,563] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:00:43,509] {logging_mixin.py:115} INFO - [2023-11-06 02:00:43,503] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:00:43,512] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:00:43,631] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.091 seconds
[2023-11-06 02:01:13,935] {processor.py:153} INFO - Started process (PID=10977) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:01:13,939] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:01:13,945] {logging_mixin.py:115} INFO - [2023-11-06 02:01:13,944] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:01:14,989] {logging_mixin.py:115} INFO - [2023-11-06 02:01:14,984] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:01:14,993] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:01:15,078] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.163 seconds
[2023-11-06 02:01:45,378] {processor.py:153} INFO - Started process (PID=11030) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:01:45,383] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:01:45,389] {logging_mixin.py:115} INFO - [2023-11-06 02:01:45,388] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:01:46,377] {logging_mixin.py:115} INFO - [2023-11-06 02:01:46,372] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:01:46,382] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:01:46,487] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.144 seconds
[2023-11-06 02:02:16,657] {processor.py:153} INFO - Started process (PID=11079) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:02:16,661] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:02:16,666] {logging_mixin.py:115} INFO - [2023-11-06 02:02:16,666] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:02:17,651] {logging_mixin.py:115} INFO - [2023-11-06 02:02:17,645] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:02:17,654] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:02:17,741] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.100 seconds
[2023-11-06 02:02:49,210] {processor.py:153} INFO - Started process (PID=11135) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:02:49,214] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:02:49,219] {logging_mixin.py:115} INFO - [2023-11-06 02:02:49,218] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:02:50,470] {logging_mixin.py:115} INFO - [2023-11-06 02:02:50,462] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:02:50,476] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:02:50,597] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.415 seconds
[2023-11-06 02:03:21,206] {processor.py:153} INFO - Started process (PID=11192) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:03:21,212] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:03:21,219] {logging_mixin.py:115} INFO - [2023-11-06 02:03:21,218] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:03:22,296] {logging_mixin.py:115} INFO - [2023-11-06 02:03:22,291] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:03:22,300] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:03:22,401] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.217 seconds
[2023-11-06 02:03:52,769] {processor.py:153} INFO - Started process (PID=11237) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:03:52,772] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:03:52,776] {logging_mixin.py:115} INFO - [2023-11-06 02:03:52,776] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:03:54,064] {logging_mixin.py:115} INFO - [2023-11-06 02:03:54,057] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:03:54,068] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:03:54,174] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.435 seconds
[2023-11-06 02:04:24,285] {processor.py:153} INFO - Started process (PID=11291) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:04:24,289] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:04:24,294] {logging_mixin.py:115} INFO - [2023-11-06 02:04:24,293] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:04:25,219] {logging_mixin.py:115} INFO - [2023-11-06 02:04:25,214] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:04:25,221] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:04:25,302] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.034 seconds
[2023-11-06 02:04:56,171] {processor.py:153} INFO - Started process (PID=11346) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:04:56,174] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:04:56,177] {logging_mixin.py:115} INFO - [2023-11-06 02:04:56,177] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:04:56,882] {logging_mixin.py:115} INFO - [2023-11-06 02:04:56,878] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:04:56,885] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:04:56,960] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.802 seconds
[2023-11-06 02:05:27,038] {processor.py:153} INFO - Started process (PID=11402) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:05:27,041] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:05:27,044] {logging_mixin.py:115} INFO - [2023-11-06 02:05:27,044] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:05:27,789] {logging_mixin.py:115} INFO - [2023-11-06 02:05:27,785] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:05:27,792] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:05:27,857] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.833 seconds
[2023-11-06 02:05:58,690] {processor.py:153} INFO - Started process (PID=11457) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:05:58,693] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:05:58,696] {logging_mixin.py:115} INFO - [2023-11-06 02:05:58,696] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:05:59,406] {logging_mixin.py:115} INFO - [2023-11-06 02:05:59,402] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:05:59,409] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:05:59,473] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.795 seconds
[2023-11-06 02:06:30,026] {processor.py:153} INFO - Started process (PID=11513) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:06:30,035] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:06:30,040] {logging_mixin.py:115} INFO - [2023-11-06 02:06:30,039] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:06:31,157] {logging_mixin.py:115} INFO - [2023-11-06 02:06:31,143] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:06:31,165] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:06:31,260] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.253 seconds
[2023-11-06 02:07:01,598] {processor.py:153} INFO - Started process (PID=11569) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:07:01,602] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:07:01,607] {logging_mixin.py:115} INFO - [2023-11-06 02:07:01,606] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:07:02,722] {logging_mixin.py:115} INFO - [2023-11-06 02:07:02,716] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:07:02,725] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:07:02,830] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.251 seconds
[2023-11-06 02:07:32,968] {processor.py:153} INFO - Started process (PID=11615) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:07:32,971] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:07:32,975] {logging_mixin.py:115} INFO - [2023-11-06 02:07:32,975] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:07:33,884] {logging_mixin.py:115} INFO - [2023-11-06 02:07:33,879] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:07:33,887] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:07:33,999] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.047 seconds
[2023-11-06 02:08:04,421] {processor.py:153} INFO - Started process (PID=11671) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:08:04,428] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:08:04,437] {logging_mixin.py:115} INFO - [2023-11-06 02:08:04,436] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:08:05,353] {logging_mixin.py:115} INFO - [2023-11-06 02:08:05,348] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:08:05,356] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:08:05,446] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.056 seconds
[2023-11-06 02:08:35,589] {processor.py:153} INFO - Started process (PID=11727) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:08:35,593] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:08:35,597] {logging_mixin.py:115} INFO - [2023-11-06 02:08:35,597] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:08:36,489] {logging_mixin.py:115} INFO - [2023-11-06 02:08:36,484] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:08:36,492] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:08:36,567] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.995 seconds
[2023-11-06 02:09:07,019] {processor.py:153} INFO - Started process (PID=11782) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:09:07,023] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:09:07,028] {logging_mixin.py:115} INFO - [2023-11-06 02:09:07,027] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:09:07,984] {logging_mixin.py:115} INFO - [2023-11-06 02:09:07,979] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:09:07,987] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:09:08,077] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.075 seconds
[2023-11-06 02:09:38,469] {processor.py:153} INFO - Started process (PID=11839) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:09:38,473] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:09:38,477] {logging_mixin.py:115} INFO - [2023-11-06 02:09:38,477] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:09:39,286] {logging_mixin.py:115} INFO - [2023-11-06 02:09:39,281] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:09:39,289] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:09:39,407] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.964 seconds
[2023-11-06 02:10:09,617] {processor.py:153} INFO - Started process (PID=11885) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:10:09,620] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:10:09,623] {logging_mixin.py:115} INFO - [2023-11-06 02:10:09,623] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:10:10,705] {logging_mixin.py:115} INFO - [2023-11-06 02:10:10,701] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:10:10,708] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:10:10,794] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.196 seconds
[2023-11-06 02:10:41,717] {processor.py:153} INFO - Started process (PID=11940) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:10:41,721] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:10:41,725] {logging_mixin.py:115} INFO - [2023-11-06 02:10:41,725] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:10:42,647] {logging_mixin.py:115} INFO - [2023-11-06 02:10:42,640] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:10:42,651] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:10:42,838] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.138 seconds
[2023-11-06 02:11:13,783] {processor.py:153} INFO - Started process (PID=11998) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:11:13,788] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:11:13,795] {logging_mixin.py:115} INFO - [2023-11-06 02:11:13,795] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:11:14,875] {logging_mixin.py:115} INFO - [2023-11-06 02:11:14,869] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:11:14,879] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:11:14,979] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.224 seconds
[2023-11-06 02:11:45,695] {processor.py:153} INFO - Started process (PID=12053) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:11:45,700] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:11:45,707] {logging_mixin.py:115} INFO - [2023-11-06 02:11:45,706] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:11:46,856] {logging_mixin.py:115} INFO - [2023-11-06 02:11:46,851] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:11:46,860] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:11:46,953] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.276 seconds
[2023-11-06 02:29:07,702] {processor.py:153} INFO - Started process (PID=12077) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:29:07,703] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:29:07,704] {logging_mixin.py:115} INFO - [2023-11-06 02:29:07,704] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:29:08,170] {logging_mixin.py:115} INFO - [2023-11-06 02:29:08,169] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:29:08,172] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:29:08,203] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.506 seconds
[2023-11-06 02:29:38,565] {processor.py:153} INFO - Started process (PID=12122) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:29:38,570] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:29:38,574] {logging_mixin.py:115} INFO - [2023-11-06 02:29:38,574] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:29:39,674] {logging_mixin.py:115} INFO - [2023-11-06 02:29:39,667] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:29:39,678] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:29:39,767] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 1.220 seconds
[2023-11-06 02:54:27,575] {processor.py:153} INFO - Started process (PID=12178) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:54:27,577] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:54:27,580] {logging_mixin.py:115} INFO - [2023-11-06 02:54:27,579] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:54:27,845] {logging_mixin.py:115} INFO - [2023-11-06 02:54:27,837] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:54:27,848] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:54:27,926] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.355 seconds
[2023-11-06 02:54:58,828] {processor.py:153} INFO - Started process (PID=12232) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:54:58,830] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:54:58,831] {logging_mixin.py:115} INFO - [2023-11-06 02:54:58,830] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:54:58,936] {logging_mixin.py:115} INFO - [2023-11-06 02:54:58,935] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:54:58,937] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:54:58,958] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.134 seconds
[2023-11-06 02:55:29,427] {processor.py:153} INFO - Started process (PID=12297) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:55:29,428] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:55:29,429] {logging_mixin.py:115} INFO - [2023-11-06 02:55:29,429] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:55:29,569] {logging_mixin.py:115} INFO - [2023-11-06 02:55:29,568] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:55:29,571] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:55:29,601] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.178 seconds
[2023-11-06 02:56:00,033] {processor.py:153} INFO - Started process (PID=12353) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:56:00,034] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:56:00,034] {logging_mixin.py:115} INFO - [2023-11-06 02:56:00,034] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:56:00,123] {logging_mixin.py:115} INFO - [2023-11-06 02:56:00,122] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:56:00,124] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:56:00,149] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.119 seconds
[2023-11-06 02:56:30,246] {processor.py:153} INFO - Started process (PID=12418) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:56:30,248] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:56:30,249] {logging_mixin.py:115} INFO - [2023-11-06 02:56:30,249] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:56:30,390] {logging_mixin.py:115} INFO - [2023-11-06 02:56:30,389] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:56:30,392] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:56:30,418] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.178 seconds
[2023-11-06 02:57:00,868] {processor.py:153} INFO - Started process (PID=12480) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:57:00,869] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:57:00,870] {logging_mixin.py:115} INFO - [2023-11-06 02:57:00,870] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:57:00,989] {logging_mixin.py:115} INFO - [2023-11-06 02:57:00,988] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:57:00,991] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:57:01,019] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.155 seconds
[2023-11-06 02:57:31,101] {processor.py:153} INFO - Started process (PID=12538) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:57:31,101] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:57:31,102] {logging_mixin.py:115} INFO - [2023-11-06 02:57:31,102] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:57:31,183] {logging_mixin.py:115} INFO - [2023-11-06 02:57:31,182] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:57:31,184] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:57:31,203] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.105 seconds
[2023-11-06 02:58:01,509] {processor.py:153} INFO - Started process (PID=12605) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:58:01,510] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:58:01,511] {logging_mixin.py:115} INFO - [2023-11-06 02:58:01,511] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:58:01,632] {logging_mixin.py:115} INFO - [2023-11-06 02:58:01,631] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:58:01,633] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:58:01,663] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.161 seconds
[2023-11-06 02:58:31,740] {processor.py:153} INFO - Started process (PID=12660) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:58:31,741] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:58:31,742] {logging_mixin.py:115} INFO - [2023-11-06 02:58:31,741] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:58:31,828] {logging_mixin.py:115} INFO - [2023-11-06 02:58:31,826] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:58:31,828] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:58:31,851] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.115 seconds
[2023-11-06 02:59:02,452] {processor.py:153} INFO - Started process (PID=12725) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:59:02,452] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:59:02,454] {logging_mixin.py:115} INFO - [2023-11-06 02:59:02,453] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:59:02,569] {logging_mixin.py:115} INFO - [2023-11-06 02:59:02,568] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:59:02,570] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:59:02,599] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.151 seconds
[2023-11-06 02:59:32,839] {processor.py:153} INFO - Started process (PID=12789) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:59:32,840] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 02:59:32,841] {logging_mixin.py:115} INFO - [2023-11-06 02:59:32,841] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:59:32,984] {logging_mixin.py:115} INFO - [2023-11-06 02:59:32,982] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 02:59:32,985] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 02:59:33,019] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.185 seconds
[2023-11-06 03:00:03,589] {processor.py:153} INFO - Started process (PID=12846) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:00:03,590] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 03:00:03,591] {logging_mixin.py:115} INFO - [2023-11-06 03:00:03,591] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:00:03,755] {logging_mixin.py:115} INFO - [2023-11-06 03:00:03,753] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 03:00:03,756] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:00:03,799] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.216 seconds
[2023-11-06 03:00:34,489] {processor.py:153} INFO - Started process (PID=12910) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:00:34,490] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 03:00:34,491] {logging_mixin.py:115} INFO - [2023-11-06 03:00:34,491] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:00:34,611] {logging_mixin.py:115} INFO - [2023-11-06 03:00:34,610] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 03:00:34,612] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:00:34,637] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.152 seconds
[2023-11-06 03:01:05,316] {processor.py:153} INFO - Started process (PID=12974) to work on /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:01:05,316] {processor.py:641} INFO - Processing file /opt/airflow/dags/raw_to_clean.py for tasks to queue
[2023-11-06 03:01:05,317] {logging_mixin.py:115} INFO - [2023-11-06 03:01:05,317] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:01:05,404] {logging_mixin.py:115} INFO - [2023-11-06 03:01:05,402] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/raw_to_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/raw_to_clean.py", line 10, in <module>
    from dags.validator import validate_schema, schema_loyalty, schema_purchases
ModuleNotFoundError: No module named 'dags'
[2023-11-06 03:01:05,404] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/raw_to_clean.py
[2023-11-06 03:01:05,426] {processor.py:161} INFO - Processing /opt/airflow/dags/raw_to_clean.py took 0.114 seconds
