[2023-11-07T05:26:58.564+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ps_etl.ps_schema_validation manual__2023-11-07T05:26:52.844047+00:00 [queued]>
[2023-11-07T05:26:58.577+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ps_etl.ps_schema_validation manual__2023-11-07T05:26:52.844047+00:00 [queued]>
[2023-11-07T05:26:58.578+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-07T05:26:58.592+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ps_schema_validation> on 2023-11-07 05:26:52.844047+00:00
[2023-11-07T05:26:58.598+0000] {standard_task_runner.py:57} INFO - Started process 2909 to run task
[2023-11-07T05:26:58.603+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ps_etl', 'ps_schema_validation', 'manual__2023-11-07T05:26:52.844047+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/ps_etl.py', '--cfg-path', '/tmp/tmpzt7rwt5a']
[2023-11-07T05:26:58.608+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask ps_schema_validation
[2023-11-07T05:26:58.660+0000] {task_command.py:416} INFO - Running <TaskInstance: ps_etl.ps_schema_validation manual__2023-11-07T05:26:52.844047+00:00 [running]> on host d2308b8de1b3
[2023-11-07T05:26:58.743+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ps_etl' AIRFLOW_CTX_TASK_ID='ps_schema_validation' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T05:26:52.844047+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T05:26:52.844047+00:00'
[2023-11-07T05:26:58.778+0000] {logging_mixin.py:151} INFO - Errors found. Details are written to error_sv_leh_2023-11-07-05-26-54.csv.
[2023-11-07T05:26:58.781+0000] {logging_mixin.py:151} INFO - Errors found. Details are written to error_sv_purchases_2023-11-07-05-26-54.csv.
[2023-11-07T05:26:58.790+0000] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2023-11-07T05:26:58.791+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-11-07T05:27:00.033+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-07T05:27:00.042+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ps_etl, task_id=ps_schema_validation, execution_date=20231107T052652, start_date=20231107T052658, end_date=20231107T052700
[2023-11-07T05:27:00.063+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-07T05:27:00.089+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
